### ISSUE TITLE
(Minor - Versioning) Current Debian release is named 1.1.3 but is seen as 1.1.1

### ISSUE THREAD

**Issue by SSUPII** [duduisonfire/rune-maker#14]
```
Preparativi per estrarre rune-maker_1.1.3_amd64.deb...
Estrazione di rune-maker (1.1.1)...
```

This is part of the output of `dpkg -i rune-maker_1.1.3_amd64.deb`. As it can be seen, internally the package is using the wrong version number.

**Comment by duduisonfire** [comment]
Thank you for your contribution, this was a small error in the compilation, we have already corrected it.
