### ISSUE TITLE
Wrong champ selected

### ISSUE THREAD

**Issue by M1guelJesus** [duduisonfire/rune-maker#2]
Hey great project!

I tried it out in a rank and the champion that the rune-maker thought i had choose was master yi when in reality I was playing yone. I think the problem is that master yi was the first ban of the blue team and the rune-maker thought that was my champ (it wasn't me that banned master yi in fact I was in the red team)

**Comment by duduisonfire** [comment]
Hey bro, thanks for your issue, I'm really glad you like it.

I will try to simulate this bug and I will fix it. Sorry for inconvenience :3

Edit. One question, u have selected Master Yi in any moment?
